# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Michael\Documents\GitHub\Assessments.MeetingMinuteTracker\SupportClasses\Meeting Item Editor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(685, 527)
        MainWindow.setMaximumSize(QtCore.QSize(685, 527))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tblItem = QtWidgets.QTableWidget(self.centralwidget)
        self.tblItem.setColumnCount(3)
        self.tblItem.setObjectName("tblItem")
        self.tblItem.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblItem.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblItem.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblItem.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.tblItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtItem = QtWidgets.QLineEdit(self.centralwidget)
        self.txtItem.setEnabled(False)
        self.txtItem.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txtItem.setObjectName("txtItem")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtActions = QtWidgets.QLineEdit(self.centralwidget)
        self.txtActions.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txtActions.setObjectName("txtActions")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtActions)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtPerson = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPerson.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txtPerson.setObjectName("txtPerson")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtPerson)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnUpdate = QtWidgets.QPushButton(self.groupBox)
        self.btnUpdate.setMinimumSize(QtCore.QSize(100, 25))
        self.btnUpdate.setMaximumSize(QtCore.QSize(100, 25))
        self.btnUpdate.setObjectName("btnUpdate")
        self.verticalLayout.addWidget(self.btnUpdate, 0, QtCore.Qt.AlignHCenter)
        self.btnClear = QtWidgets.QPushButton(self.groupBox)
        self.btnClear.setMinimumSize(QtCore.QSize(100, 25))
        self.btnClear.setMaximumSize(QtCore.QSize(100, 25))
        self.btnClear.setObjectName("btnClear")
        self.verticalLayout.addWidget(self.btnClear, 0, QtCore.Qt.AlignHCenter)
        self.btnSaveQuit = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveQuit.sizePolicy().hasHeightForWidth())
        self.btnSaveQuit.setSizePolicy(sizePolicy)
        self.btnSaveQuit.setMinimumSize(QtCore.QSize(100, 25))
        self.btnSaveQuit.setMaximumSize(QtCore.QSize(100, 25))
        self.btnSaveQuit.setObjectName("btnSaveQuit")
        self.verticalLayout.addWidget(self.btnSaveQuit, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tblItem.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item"))
        item = self.tblItem.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Actions Required"))
        item = self.tblItem.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Person Responsible"))
        self.label.setText(_translate("MainWindow", "Item: "))
        self.label_2.setText(_translate("MainWindow", "Actions Required: "))
        self.label_3.setText(_translate("MainWindow", "Person Responsible:"))
        self.groupBox.setTitle(_translate("MainWindow", "Actions:"))
        self.btnUpdate.setText(_translate("MainWindow", "Update"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.btnSaveQuit.setText(_translate("MainWindow", "Save and Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

